#!/usr/bin/env bash

set -e

apt-get update
apt-get install -y wget \
                   software-properties-common

wget -nv -O /usr/local/bin/confd https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-amd64
chmod +x /usr/local/bin/confd

apt-get clean
rm -rf /var/lib/apt/lists/*
